# Generated by Django 4.0.2 on 2022-02-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctiondisplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='type',
            new_name='bike_type',
        ),
    ]
