# Generated by Django 4.0.2 on 2022-02-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='owner',
            new_name='user',
        ),
    ]
