# Generated by Django 4.0.2 on 2022-02-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_order_items_order_item_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='auction',
        ),
    ]
