# Generated by Django 4.0.2 on 2022-02-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='picture',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
